# Placed by provision.py; see the `files` section of provision/config.yaml.
format = "$time $username $custom $all"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"

[username]
show_always = true
format = "[$user]($style)"
style_user = "#808080"
style_root = "red"
